# Generated by Django 3.2.16 on 2025-03-08 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
