# Generated by Django 3.2.16 on 2025-03-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20250306_0025'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_subscription'),
        ),
    ]
