# Generated by Django 3.2.16 on 2025-03-09 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_auto_20250309_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
