# Generated by Django 3.2.16 on 2025-03-09 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0005_auto_20250309_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.foodgramuserinterface', verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.foodgramuserinterface', verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_subscription'),
        ),
    ]
