# Generated by Django 3.2.16 on 2025-03-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250309_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shopping_cart',
            new_name='recipe',
        ),
    ]
