# Generated by Django 3.2.16 on 2025-03-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20250313_1523'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredientinrecipe',
        ),
    ]
