# Generated by Django 3.2.16 on 2025-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favorites_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipes/image/', verbose_name='Изображение'),
        ),
    ]
