# Generated by Django 3.2.16 on 2025-03-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuserinterface',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
