# Generated by Django 3.2.16 on 2025-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuserinterface_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuserinterface',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Почта'),
        ),
    ]
