from typing import Final


MAX_LENGTH_TAG: Final = 32
MAX_LENGTH_INGREDIENT: Final = 128
MAX_LENGTH_UNIT: Final = 64
MAX_LENGTH_RECIPE: Final = 256
MIN_VALUE_COOKING_TIME: Final = 1
MIN_VALUE_INGREDIENT_AMOUNT: Final = 1
